{{- if .Values.mysql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wordpress-mysql.fullname" . }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels: {{- include "mysql.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.mysql.strategy.type }}
  template:
    metadata:
      labels: {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "wordpress-mysql.serviceAccountName" . }}
      securityContext:
      containers:
      - name: {{ template "mysql.fullname" . }}
        securityContext:
          {{- toYaml .Values.mysql.securityContext | nindent 12 }}
        image: {{ .Values.mysql.image.repository }}
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        env:
          - name: {{ .Values.mysql.env.name }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.env.secretKeyRef.name }}
                key: {{ .Values.mysql.env.secretKeyRef.key }}
        ports:
          - containerPort: {{ .Values.mysql.ports.containerPort }}
            name: {{ .Values.mysql.ports.name }}
            protocol: {{ .Values.mysql.ports.protocol }}
        volumeMounts:
          - name: {{ template "mysql.volumes" . }}
            mountPath: {{ .Values.mysql.volumeMounts.mountPath }}
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
      volumes:
        - name: {{ template "mysql.volumes" . }}
          persistentVolumeClaim:
            claimName: {{ template "mysql.persistentVolumeClaim" . }}

    {{- with .Values.mysql.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.mysql.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.mysql.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
