{{- if .Values.wordpress.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  # The default name in helpers.tpl + The release name
  name: {{ template "wordpress.fullname" . }}-{{ .Release.Name }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels: {{- include "wordpress.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.wordpress.strategy.type }}
  template:
    metadata:
      labels: {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "wordpress-mysql.serviceAccountName" . }}
      securityContext:
      containers:
        - name: {{ template "wordpress.fullname" . }}
          securityContext:
            {{- toYaml .Values.wordpress.securityContext | nindent 12 }}
          image: {{ .Values.wordpress.image.repository }}
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          env:
            - name: {{ .Values.wordpress.env.name }}
              value:  {{ .Values.wordpress.env.value }}
            - name: {{ .Values.wordpress.env2.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpress.env2.secretKeyRef.name }}
                  key: {{ .Values.wordpress.env2.secretKeyRef.key }}
          ports:
            - containerPort: {{ .Values.wordpress.ports.containerPort }}
              name: {{ .Values.wordpress.ports.name }}
              protocol: {{ .Values.wordpress.ports.protocol }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

          volumeMounts:
          - name: {{ template "wordpress.volumes" . }}
            mountPath: {{ .Values.wordpress.volumeMounts.mountPath }}
      volumes:
      - name: {{ template "wordpress.volumes" . }}
        persistentVolumeClaim:
          claimName: {{ template "wordpress.persistentVolumeClaim" . }}-{{ .Release.Name }}

    {{- with .Values.wordpress.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.wordpress.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.wordpress.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}
