{{- if and .Values.mysql.enabled .Values.mysql.PersistentVolumeClaim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # The default name in helpers.tpl + The release name
  name: {{ template "mysql.persistentVolumeClaim" . }}-{{ .Release.Name }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mysql.PersistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: "{{ .Values.mysql.PersistentVolumeClaim.storage }}"
{{- end -}}