{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.secret" . }}-{{ .Release.Name }}
type: Opaque
data:
  mysqlpass: {{ randAlphaNum 10 | b64enc | quote }}
{{  end }}