{{- if and .Values.wordpress.enabled .Values.wordpress.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  # The default name in helpers.tpl + The release name
  name: {{ template "wordpress.fullname" . }}-{{ .Release.Name }}
  labels: {{- include "wordpress.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: {{ .Values.wordpress.ports.containerPort }}
      protocol: {{ .Values.wordpress.ports.protocol }}
  selector: {{- include "wordpress.selectorLabels" . | nindent 4 }}
  type: {{ .Values.wordpress.service.type }}
{{- end }}
