{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "wordpress-mysql.serviceAccountName" . }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
          {{- include "wordpress.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}