{{- if and .Values.mysql.enabled .Values.mysql.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  # The default name in helpers.tpl + The release name
  name: {{ template "mysql.fullname" . }}-{{ .Release.Name }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.ports.containerPort }}
      protocol: {{ .Values.mysql.ports.protocol }}
  selector: {{- include "mysql.selectorLabels" . | nindent 4 }}
  type: {{ .Values.mysql.service.type }}
  clusterIP: {{ .Values.mysql.service.clusterIP }}
{{- end }}
